server:
  port: 8088

spring:
  session:
    store-type: none
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:~/data/angular-guild

app:
  origins:
    - http://localhost:9876
    - http://localhost:4200
    - http://www.yz.com
    - https://mengyunzhi.github.io/